name: splitin_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.3.0
  floating_navbar: ^3.0.0
  convex_bottom_bar: ^3.0.0
  provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/montserrat.ttf
        - asset: fonts/montserrat-bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/images/
